const $=(s,r=document)=>r.querySelector(s),app=$("#app");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const pretty=v=>JSON.stringify(v,null,2),short=v=>String(v||"").slice(0,8);
const state={documents:[],health:null,last:null,timer:null};

function toast(message,ok=true){const n=$("#toast");n.textContent=message;n.className=`show${ok?"":" bad"}`;clearTimeout(n.timer);n.timer=setTimeout(()=>n.className="",4200)}
async function request(path,options={}){const r=await fetch(path,options),type=r.headers.get("content-type")||"",body=type.includes("json")?await r.json():await r.text();state.last={status:r.status,path,body,at:new Date().toLocaleTimeString("zh-CN",{hour12:false})};if(!r.ok){const d=Array.isArray(body?.detail)?body.detail.map(x=>x.msg).join("；"):body?.detail;throw new Error(body?.message||d||`${r.status} ${r.statusText}`)}return body}
async function run(button,fn){if(button)button.disabled=true;try{return await fn()}catch(e){toast(e.message,false);throw e}finally{if(button)button.disabled=false}}
function active(name,label,parent="控制台"){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.nav===name));$("#crumb").innerHTML=`${esc(parent)} &nbsp;/&nbsp; <strong>${esc(label)}</strong>`}
function head(title,desc,actions=""){return `<div class="pagehead"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${actions?`<div class="actions">${actions}</div>`:""}</div>`}
function badge(s){const m={ready:"已索引",pending:"待处理",indexing:"索引中",failed:"处理失败",deleting:"删除中",deleted:"已删除"};return `<span class="badge ${esc(s)}">${esc(m[s]||s)}</span>`}
async function health(){try{const r=await fetch("/health");state.health=await r.json();const ok=!!state.health.ready;$("#side-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"服务运行中":"服务异常"}`;$("#top-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"全部依赖正常":"存在异常依赖"}`}catch{state.health=null;$("#side-health").innerHTML='<span class="dot bad"></span>API 不可用';$("#top-health").innerHTML='<span class="dot bad"></span>连接失败'}drawHealth()}
async function docs(){state.documents=await request('/v1/documents');return state.documents}

function documentsPage(){
 active('documents','文档');
 app.innerHTML=head('文档','查找团队知识，查看原文件与索引状态。','<a class="btn" href="#/documents/new">录入文档</a>')+`
 <section class="panel document-filters"><form id="document-query">
 <div class="query-heading"><strong>筛选文档</strong><span>按条件组合查询</span></div>
 <div class="query-grid">
 <label>Title<input name="title" placeholder="输入文档标题" autocomplete="off"></label>
 <label>Team<select name="team"><option value="">全部团队</option>${teams.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></label>
 <label>Project<input name="project" placeholder="输入项目名称" autocomplete="off"></label>
 <label>ID<input name="document_id" placeholder="输入完整或部分文档 ID" autocomplete="off"></label>
 <label>操作人<input name="operator" placeholder="输入操作人" autocomplete="off"></label>
 <label>状态<select name="status"><option value="">全部状态</option>${['ready','pending','indexing','failed','deleting','deleted'].map(s=>`<option value="${s}">${({ready:'已索引',pending:'待处理',indexing:'索引中',failed:'处理失败',deleting:'删除中',deleted:'已删除'})[s]}</option>`).join('')}</select></label>
 </div><div class="query-footer"><span>支持组合筛选，点击查询或按 Enter 更新结果。</span><div class="actions"><button type="reset" class="btn secondary">重置</button><button class="btn" type="submit">查询</button></div></div>
 </form></section>
 <section class="panel" id="document-results"><div class="document-tablehead"><div><strong>文档列表</strong><span id="document-total"></span></div><button class="rowbtn" id="document-refresh">刷新</button></div>
 <div class="tablewrap"><table class="document-table"><colgroup><col style="width:48px"><col style="width:230px"><col style="width:88px"><col style="width:76px"><col style="width:140px"><col style="width:170px"><col style="width:54px"><col style="width:90px"><col style="width:180px"></colgroup>
 <thead><tr><th>序号</th><th>Title</th><th>ID</th><th>Team</th><th>Project</th><th>Description</th><th>版本</th><th>状态</th><th>操作</th></tr></thead><tbody id="document-rows"></tbody></table></div>
 <div class="document-pagination"><span id="document-range" aria-live="polite"></span><div id="document-pages" class="document-pages"></div></div></section>`;
 const form=$('#document-query'),rows=$('#document-rows'),pager=$('#document-pages');
 let filters={},page=1,sequence=0,controller;
 const current=()=>$('#document-query')===form;
 const draw=result=>{
  const start=(result.page-1)*20,pages=Math.max(1,Math.ceil(result.total/20));
  $('#document-total').textContent=`共 ${result.total} 份`;
  rows.innerHTML=result.items.length?result.items.map((d,i)=>{
   const chars=Array.from(d.description||''),description=chars.length>20?chars.slice(0,20).join('')+'…':chars.join('');
   return `<tr><td>${start+i+1}</td><td title="${esc(d.title)}"><span class="title">${esc(d.title)}</span></td><td class="mono" title="${esc(d.document_id)}">${esc(short(d.document_id))}</td><td>${esc(d.team||'—')}</td><td title="${esc(d.project)}">${esc(d.project||'—')}</td><td class="document-description" title="${esc(d.description)}">${esc(description||'—')}</td><td class="mono">v${d.version}</td><td>${badge(d.status)}</td><td class="document-actions"><div class="rowactions"><a class="rowbtn" href="#/documents/${encodeURIComponent(d.document_id)}">查看</a>${fileActions(d.file_url)}<details><summary>更多</summary><div class="document-menu"><button class="rowbtn" data-action="rebuild" data-id="${esc(d.document_id)}" ${['deleting','deleted'].includes(d.status)?'disabled':''}>重建</button><button class="rowbtn danger" data-action="delete" data-id="${esc(d.document_id)}" ${['deleting','deleted'].includes(d.status)?'disabled':''}>删除</button></div></details></div></td></tr>`;
  }).join(''):'<tr><td colspan="9" class="empty">没有符合条件的文档，请调整筛选条件。</td></tr>';
  $('#document-range').textContent=result.total?`显示 ${start+1}–${start+result.items.length} 条，共 ${result.total} 条`:'共 0 条';
  const numbers=[...new Set([1,...Array.from({length:5},(_,i)=>page-2+i).filter(n=>n>1&&n<pages),pages])].sort((a,b)=>a-b);
  pager.innerHTML='<span>20 条 / 页</span>'+`<button class="page-button" data-page="${page-1}" ${page===1?'disabled':''}>上一页</button>`+numbers.map((n,i)=>`${i&&n-numbers[i-1]>1?'<span>…</span>':''}<button class="page-button ${n===page?'selected':''}" aria-label="第 ${n} 页" ${n===page?'aria-current="page"':''} data-page="${n}">${n}</button>`).join('')+`<button class="page-button" data-page="${page+1}" ${page>=pages?'disabled':''}>下一页</button>`;
 };
 const load=async()=>{
  clearTimeout(state.timer);controller?.abort();controller=new AbortController();const turn=++sequence;
  $('#document-results').setAttribute('aria-busy','true');
  rows.innerHTML='<tr><td colspan="9" class="empty">加载中…</td></tr>';pager.innerHTML='';$('#document-range').textContent='';
  try{
   const result=await request('/v1/documents/query?'+new URLSearchParams({...filters,page}),{signal:controller.signal});
   if(!current()||turn!==sequence)return;
   const last=Math.max(1,Math.ceil(result.total/20));if(page>last){page=last;return await load()}
   draw(result);
   if(result.items.some(d=>['pending','indexing','deleting'].includes(d.status)))state.timer=setTimeout(()=>{if(current())load()},3000);
  }catch(e){if(e.name==='AbortError'||!current()||turn!==sequence)return;rows.innerHTML='<tr><td colspan="9" class="empty">查询失败，请点击刷新重试。</td></tr>';$('#document-total').textContent='';toast(e.message,false)}
  finally{if(current()&&turn===sequence)$('#document-results').setAttribute('aria-busy','false')}
 };
 form.onsubmit=e=>{e.preventDefault();filters=Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,v.trim()]).filter(([,v])=>v));page=1;load()};
 form.onreset=()=>{filters={};page=1;load()};
 $('#document-refresh').onclick=()=>load();
 pager.onclick=e=>{const b=e.target.closest('[data-page]');if(b&&!b.disabled){page=Number(b.dataset.page);load()}};
 rows.addEventListener('toggle',e=>{const details=e.target;if(details.tagName!=='DETAILS'||!details.open)return;rows.querySelectorAll('details[open]').forEach(other=>{if(other!==details)other.open=false});const box=details.querySelector('summary').getBoundingClientRect(),menu=details.querySelector('.document-menu');menu.style.left=Math.max(8,Math.min(box.right-120,innerWidth-128))+'px';menu.style.top=Math.max(8,box.top-menu.offsetHeight-8)+'px'},true);
 $('.tablewrap',$('#document-results')).onscroll=()=>rows.querySelectorAll('details[open]').forEach(d=>d.open=false);
 rows.onclick=async e=>{const b=e.target.closest('button[data-action]');if(!b||b.disabled)return;const deleting=b.dataset.action==='delete';if(deleting&&!confirm(`确认删除文档 ${b.dataset.id}？此操作会同时清除索引。`))return;try{await run(b,async()=>{await request(`/v1/documents/${encodeURIComponent(b.dataset.id)}${deleting?'':'/reindex'}`,{method:deleting?'DELETE':'POST'});toast(deleting?'已提交删除任务':'已提交重建任务')});if(current())await load()}catch{}};
 load();
}

const teams=["wallet","member","devops","data","event"];
const jsonPost=body=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
async function uploadFile(file){const form=new FormData();form.append("file",file);return request("/v1/files",{method:"POST",body:form})}
function fileActions(url){return `<a class="rowbtn file-icon" href="${esc(url)}" target="_blank" rel="noopener" title="查看原文件" aria-label="查看原文件"><i class="ph ph-eye" aria-hidden="true"></i></a><a class="rowbtn file-icon" href="${esc(url)}?download=true" download title="下载原文件" aria-label="下载原文件"><i class="ph ph-download-simple" aria-hidden="true"></i></a>`}
function newPage(){
 active("new","录入文档","文档");
 app.innerHTML=head("录入文档","先上传原文件，再填写信息并提交索引。支持 Markdown、TXT 和 PDF。",'<a class="btn secondary" href="#/documents">返回文档</a>')+`<section class="panel"><div class="body"><form id="ingest" class="grid"><label class="full">源文件<input id="file" type="file" accept=".md,.markdown,.txt,.pdf" required><span id="uploadstatus" class="help" role="status">选择文件后自动上传。</span></label><label>标题 *<input name="title" required maxlength="500"></label><label>团队<select name="team"><option value="">请选择</option>${teams.map(t=>`<option value="${t}">${t}</option>`).join("")}</select></label><label>项目<input name="project"></label><label>操作人<input name="operator"></label><label class="full">描述<textarea name="description"></textarea></label><label class="full">Metadata JSON Object<textarea name="metadata" spellcheck="false">{}</textarea></label><div class="formactions full"><a class="btn secondary" href="#/documents">取消</a><button id="submitdoc" class="btn" disabled>提交索引</button></div></form></div></section>`;
 const form=$("#ingest"),button=$("#submitdoc"),status=$("#uploadstatus");let uploaded=null,sequence=0;
 $("#file").onchange=async e=>{const token=++sequence,file=e.target.files[0];uploaded=null;button.disabled=true;if(!file){status.textContent="请选择文件";return}status.textContent="上传中…";if(!form.elements.title.value)form.elements.title.value=file.name;try{const result=await uploadFile(file);if(token!==sequence)return;uploaded=result;status.innerHTML=`上传完成 · ${esc(result.filename)} ${fileActions(result.url)}`;button.disabled=false}catch(error){if(token===sequence){status.textContent=`上传失败：${error.message}`;toast(error.message,false)}}};
 form.onsubmit=async e=>{e.preventDefault();await run(button,async()=>{if(!uploaded)throw Error("请先完成文件上传");const data=new FormData(form),metadata=JSON.parse(data.get("metadata")||"{}");if(!metadata||Array.isArray(metadata)||typeof metadata!=="object")throw Error("Metadata 必须是 JSON Object");const title=data.get("title").trim();if(!title)throw Error("标题必填");const payload={file_url:uploaded.url,title,metadata};for(const field of ["team","project","description","operator"])payload[field]=data.get(field).trim()||null;const result=await request("/v1/documents",jsonPost(payload));toast(`文档已提交：${short(result.document_id)}`);location.hash="#/documents"})};
}
function detailPage(id){
 active("documents","文档详情","文档");app.innerHTML=head("文档详情","查看原文件、下载，或上传新文件替换并重新索引。",'<a class="btn secondary" href="#/documents">返回文档列表</a>')+'<div id="detail"><div class="empty">加载中…</div></div>';
 docs().then(()=>{const d=state.documents.find(x=>String(x.document_id)===id);if(!d)throw Error("未找到该文档");$("#detail").innerHTML=`<div class="detail"><section class="panel"><div class="panelhead"><h2>${esc(d.title)}</h2>${badge(d.status)}</div><div class="body grid">${["title","team","project","operator","description"].map(k=>`<label class="${k==="description"?"full":""}">${({title:"标题",team:"团队",project:"项目",operator:"操作人",description:"描述"})[k]}<${k==="description"?"textarea readonly":"input readonly value=\""+esc(d[k]||"")+"\""}>${k==="description"?esc(d[k]||"")+"</textarea>":""}</label>`).join("")}<p class="help full">ID ${esc(d.document_id)} · v${d.version}</p>${d.last_error?`<pre class="chunk full">${esc(d.last_error)}</pre>`:""}<label class="full">Metadata<textarea readonly>${esc(pretty(d.metadata||{}))}</textarea></label></div></section><aside class="panel"><div class="panelhead"><h2>原文件</h2></div><div class="body"><div class="actions">${fileActions(d.file_url)}</div><form id="reindex"><label style="margin-top:20px">替换文件（可选）<input id="newfile" type="file" accept=".md,.markdown,.txt,.pdf"></label><p id="reuploadstatus" class="help" role="status">留空则使用现有文件重建。</p><button class="btn" style="margin-top:12px">提交更新 / 重建</button></form><div class="dangerzone"><button id="remove" class="btn danger">删除文档</button><p class="help">删除文档和索引，保留独立上传的原文件。</p></div></div></aside></div>`;
 const form=$("#reindex"),button=form.querySelector("button"),status=$("#reuploadstatus");let uploaded=null,sequence=0;
 $("#newfile").onchange=async e=>{const token=++sequence,file=e.target.files[0];uploaded=null;button.disabled=!!file;if(!file){status.textContent="将使用现有文件重建";return}status.textContent="上传中…";try{const result=await uploadFile(file);if(token!==sequence)return;uploaded=result;status.textContent=`上传完成：${result.filename}`;button.disabled=false}catch(error){if(token===sequence){status.textContent=`上传失败：${error.message}`;toast(error.message,false)}}};
 form.onsubmit=async e=>{e.preventDefault();await run(button,async()=>{if($("#newfile").files.length&&!uploaded)throw Error("请先完成文件上传");const r=await request(`/v1/documents/${encodeURIComponent(id)}/reindex`,jsonPost({file_url:uploaded?.url||null}));toast(`已提交更新，目标版本 v${r.version}`);detailPage(id)})};
 $("#remove").onclick=e=>{if(confirm(`确认删除文档 ${d.title}？`))run(e.currentTarget,async()=>{await request(`/v1/documents/${encodeURIComponent(id)}`,{method:"DELETE"});toast("已提交删除任务");location.hash="#/documents"})};
 }).catch(e=>{$("#detail").innerHTML='<div class="empty">文档不存在或加载失败</div>';toast(e.message,false)});
}

function searchPage(){active("search","检索");app.innerHTML=head("检索","使用自然语言查询已完成索引的文档，并检查召回分数与 Chunk 来源。")+`<section class="searchbox"><form id="search"><label>问题<textarea id="query" class="query" required placeholder="输入希望从知识库中检索的问题…"></textarea></label><div class="searchcontrols"><div class="topk"><label>Top-K（1–10）<input id="topk" type="number" min="1" max="10" value="5" required></label><span class="help">控制返回的最大结果数</span></div><button class="btn"><i class="ph ph-magnifying-glass"></i>开始检索</button></div></form></section><div class="resultshead"><h2>检索结果</h2><span id="summary" class="help">提交问题后显示结果</span></div><section id="results"></section>`;$("#search").onsubmit=async e=>{e.preventDefault();await run(e.submitter,async()=>{const start=performance.now(),query=$("#query").value.trim(),top_k=Math.max(1,Math.min(10,Number($("#topk").value)));$("#topk").value=top_k;const items=await request("/v1/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,top_k})});$("#summary").textContent=`找到 ${items.length} 条结果 · ${(performance.now()-start).toFixed(0)} ms · Top-K ${top_k}`;$("#results").innerHTML=items.length?items.map((x,i)=>`<article class="result"><div class="rank">${i+1}</div><div class="resultmain"><div class="resulttitle"><strong>${esc(x.title||x.file_url)}</strong><span class="score">${Number(x.score).toFixed(6)}</span></div><p>${esc(x.content)}</p><a class="rowbtn" href="#/chunks?document=${encodeURIComponent(x.document_id)}&chunk=${encodeURIComponent(x.chunk_id)}">查看完整 Chunk →</a></div><div class="resultmeta"><span>文档 ID<br><code title="${esc(x.document_id)}">${esc(short(x.document_id))}</code></span><span>Chunk ID<br><code title="${esc(x.chunk_id)}">${esc(short(x.chunk_id))}</code></span><span>${esc(x.file_url)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</span></div></article>`).join(""):'<div class="panel"><div class="empty">没有召回有效结果</div></div>'})}}

function chunksPage(params){active("chunks","Chunk 查询");app.innerHTML=head("Chunk 查询","使用 Document ID 和 Chunk ID 精确读取 Qdrant 中保存的原始切块。")+`<section class="panel"><div class="panelhead"><div><h2>精确定位</h2><p>两个 UUID 必须来自同一条检索结果。</p></div></div><div class="body"><form id="chunkform" class="grid"><label>Document ID<input id="docid" class="mono" required value="${esc(params.get("document")||"")}" placeholder="完整 Document UUID"></label><label>Chunk ID<input id="chunkid" class="mono" required value="${esc(params.get("chunk")||"")}" placeholder="完整 Chunk UUID"></label><div class="formactions full"><button class="btn"><i class="ph ph-crosshair"></i>读取 Chunk</button></div></form></div></section><section id="chunkresult"></section>`;const submit=b=>run(b,async()=>{const d=$("#docid").value.trim(),c=$("#chunkid").value.trim(),x=await request(`/v1/documents/${encodeURIComponent(d)}/chunks/${encodeURIComponent(c)}`);$("#chunkresult").innerHTML=`<section class="panel"><div class="panelhead"><div><h2>${esc(x.title||"Chunk 内容")}</h2><p>${esc(x.file_url)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</p></div><span class="score">${esc(short(x.chunk_id))}</span></div><div class="body"><pre class="chunk">${esc(x.content)}</pre><p class="help">Metadata · <code>${esc(pretty(x.metadata||{}))}</code></p></div></section>`});$("#chunkform").onsubmit=e=>{e.preventDefault();submit(e.submitter)};if(params.get("document")&&params.get("chunk"))submit($("#chunkform button"))}

function drawHealth(){const grid=$("#healthgrid");if(!grid)return;const deps=state.health?.dependencies;if(!deps){grid.innerHTML='<div class="empty">无法读取依赖状态</div>';return}const labels={postgresql:"PostgreSQL",rabbitmq:"RabbitMQ",qdrant:"Qdrant",ollama:"Ollama",worker:"索引 Worker"};grid.innerHTML=Object.entries({...deps,worker:deps.worker}).map(([n,ok])=>`<div class="healthitem"><div><strong>${esc(labels[n]||n)}</strong>${n==="worker"?'<p class="help">每 10 秒发送心跳，30 秒过期；需有活跃消费者。</p>':""}</div>${ok===undefined?'<span class="badge">未知</span>':`<span class="badge ${ok?"ready":"failed"}">${ok?"正常":"异常"}</span>`}</div>`).join("")}
function systemPage(){active("system","系统状态");app.innerHTML=head("系统状态","检查 API、基础设施及索引 Worker，并查看最近一次 HTTP 响应。",'<button id="refreshhealth" class="btn secondary"><i class="ph ph-arrows-clockwise"></i>重新检查</button>')+`<section class="panel"><div class="panelhead"><div><h2>服务依赖</h2><p>状态来自 GET /health。</p></div></div><div class="body"><div id="healthgrid" class="healthgrid"><div class="empty">检查中…</div></div></div></section><section class="panel"><div class="panelhead"><div><h2>最近 HTTP 响应</h2><p>用于学习与排查接口契约。</p></div><button id="clear" class="btn secondary small">清空</button></div><div class="body"><pre id="log" class="log">${esc(state.last?pretty(state.last):"尚无请求")}</pre></div></section>`;health().then(drawHealth);$("#refreshhealth").onclick=e=>run(e.currentTarget,async()=>{await health();drawHealth();toast("状态已刷新")});$("#clear").onclick=()=>{state.last=null;$("#log").textContent="尚无请求"}}

function route(){clearTimeout(state.timer);document.body.classList.remove("navopen");const raw=(location.hash||"#/documents").slice(1),[path,q=""]=raw.split("?"),s=path.split("/").filter(Boolean),p=new URLSearchParams(q);if(s[0]==="documents"&&s[1]==="new")newPage();else if(s[0]==="documents"&&s[1])detailPage(decodeURIComponent(s[1]));else if(s[0]==="documents")documentsPage();else if(s[0]==="search")searchPage();else if(s[0]==="chunks")chunksPage(p);else if(s[0]==="system")systemPage();else location.hash="#/documents";requestAnimationFrame(()=>app.focus({preventScroll:true}))}
$("#menu").onclick=()=>document.body.classList.toggle("navopen");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.body.classList.remove("navopen"));addEventListener("hashchange",route);health();route();setInterval(health,15000);
