const $=(s,r=document)=>r.querySelector(s),app=$("#app");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const pretty=v=>JSON.stringify(v,null,2),short=v=>String(v||"").slice(0,8);
const state={documents:[],health:null,last:null,timer:null};

function toast(message,ok=true){const n=$("#toast");n.textContent=message;n.className=`show${ok?"":" bad"}`;clearTimeout(n.timer);n.timer=setTimeout(()=>n.className="",4200)}
async function request(path,options={}){const r=await fetch(path,options),type=r.headers.get("content-type")||"",body=type.includes("json")?await r.json():await r.text();state.last={status:r.status,path,body,at:new Date().toLocaleTimeString("zh-CN",{hour12:false})};if(!r.ok){const d=Array.isArray(body?.detail)?body.detail.map(x=>x.msg).join("；"):body?.detail;throw new Error(body?.message||d||`${r.status} ${r.statusText}`)}return body}
async function run(button,fn){if(button)button.disabled=true;try{return await fn()}catch(e){toast(e.message,false);throw e}finally{if(button)button.disabled=false}}
function active(name,label,parent="控制台"){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.nav===name));$("#crumb").innerHTML=`${esc(parent)} &nbsp;/&nbsp; <strong>${esc(label)}</strong>`}
function head(title,desc,actions=""){return `<div class="pagehead"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${actions?`<div class="actions">${actions}</div>`:""}</div>`}
function badge(s){const m={ready:"已索引",pending:"待处理",indexing:"索引中",failed:"处理失败",deleting:"删除中",deleted:"已删除"};return `<span class="badge ${esc(s)}">${esc(m[s]||s)}</span>`}
async function health(){try{const r=await fetch("/health");state.health=await r.json();const ok=!!state.health.ready;$("#side-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"服务运行中":"服务异常"}`;$("#top-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"全部依赖正常":"存在异常依赖"}`}catch{state.health=null;$("#side-health").innerHTML='<span class="dot bad"></span>API 不可用';$("#top-health").innerHTML='<span class="dot bad"></span>连接失败'}drawHealth()}
let documentRequest=0;
async function docs(){const params=new URLSearchParams();for(const [key,id] of [["q","filter"],["team","query-team"],["status","status"],["project","query-project"],["operator","query-operator"]]){const value=$("#"+id)?.value.trim();if(value)params.set(key,value)}const sequence=++documentRequest,result=await request("/v1/documents"+(params.size?"?"+params:""));if(sequence===documentRequest)state.documents=result;return state.documents}

function documentsPage(){active("documents","文档");app.innerHTML=head("文档","管理已录入的文档，查看索引状态并执行更新、重建或删除。",'<a class="btn" href="#/documents/new"><i class="ph ph-plus"></i>录入文档</a>')+`<section id="stats" class="stats"></section><section class="panel"><div class="body"><div class="toolbar"><div class="searchinput"><i class="ph ph-magnifying-glass"></i><input id="filter" type="search" aria-label="文档关键词" placeholder="搜索标题、描述、项目、操作人或 ID"></div><select id="query-team" aria-label="团队"><option value="">全部团队</option>${teams.map(t=>`<option value="${t}">${t}</option>`).join("")}</select><input id="query-project" aria-label="项目筛选" placeholder="项目（精确匹配）"><input id="query-operator" aria-label="操作人筛选" placeholder="操作人（精确匹配）"><select id="status" aria-label="状态"><option value="">全部状态</option><option value="ready">已索引</option><option value="pending">待处理</option><option value="indexing">索引中</option><option value="failed">处理失败</option><option value="deleting">删除中</option><option value="deleted">已删除</option></select><button id="refresh" class="btn secondary"><i class="ph ph-arrows-clockwise"></i>刷新</button></div><div class="tablewrap"><table><thead><tr><th>文档标题 / 项目</th><th>ID</th><th>版本</th><th>状态</th><th>Metadata</th><th>操作</th></tr></thead><tbody id="rows"><tr><td colspan="6" class="empty">加载中…</td></tr></tbody></table></div></div></section>`;
 const draw=()=>{if(!$("#rows"))return;const items=state.documents,counts=state.documents.reduce((a,d)=>(a[d.status]=(a[d.status]||0)+1,a),{});$("#stats").innerHTML=[["查询结果",state.documents.length,"files"],["已索引",counts.ready||0,"check-circle"],["处理中",(counts.pending||0)+(counts.indexing||0),"clock-countdown"],["处理失败",counts.failed||0,"warning-circle"]].map(x=>`<div class="stat"><span>${x[0]}<i class="ph ph-${x[2]}"></i></span><strong>${x[1]}</strong></div>`).join("");$("#rows").innerHTML=items.length?items.map(d=>`<tr><td><span class="title">${esc(d.title||"未命名文档")}</span><span class="source">${esc(d.project||"—")} · ${esc(d.team||"—")}</span></td><td class="mono" title="${esc(d.document_id)}">${esc(short(d.document_id))}</td><td>v${d.version}</td><td>${badge(d.status)}</td><td class="mono">${Object.keys(d.metadata||{}).length?Object.keys(d.metadata).length+" fields":"—"}</td><td><div class="rowactions"><a class="rowbtn" href="#/documents/${encodeURIComponent(d.document_id)}">详情 / 更新</a>${fileActions(d.file_url)}<button class="rowbtn rebuild" data-id="${esc(d.document_id)}">重建</button><button class="rowbtn danger delete" data-id="${esc(d.document_id)}">删除</button></div></td></tr>`).join(""):'<tr><td colspan="6"><div class="empty"><i class="ph ph-files"></i>没有符合条件的文档</div></td></tr>'};
 const refresh=async b=>run(b,async()=>{await docs();draw();schedule(draw)});let queryTimer;const query=()=>{clearTimeout(queryTimer);queryTimer=setTimeout(()=>{if($("#filter"))refresh(null).catch(()=>{})},300)};for(const id of ["filter","query-project","query-operator"])$("#"+id).oninput=query;for(const id of ["status","query-team"])$("#"+id).onchange=()=>{clearTimeout(queryTimer);refresh(null).catch(()=>{})};$("#refresh").onclick=e=>refresh(e.currentTarget);$("#rows").onclick=async e=>{const b=e.target.closest("button[data-id]");if(!b)return;if(b.classList.contains("rebuild"))await run(b,async()=>{const r=await request(`/v1/documents/${encodeURIComponent(b.dataset.id)}/reindex`,{method:"POST"});toast(`已提交重建，目标版本 v${r.version}`);await docs();draw()});if(b.classList.contains("delete")&&confirm(`确认删除文档 ${b.dataset.id}？此操作会同时清除索引。`))await run(b,async()=>{await request(`/v1/documents/${encodeURIComponent(b.dataset.id)}`,{method:"DELETE"});toast("已提交删除任务");await docs();draw()})};docs().then(()=>{draw();schedule(draw)}).catch(e=>{$("#rows").innerHTML='<tr><td colspan="6" class="empty">文档加载失败</td></tr>';toast(e.message,false)})}
function schedule(draw){clearTimeout(state.timer);if(state.documents.some(d=>["pending","indexing","deleting"].includes(d.status)))state.timer=setTimeout(async()=>{try{await docs();draw();schedule(draw)}catch{}},3000)}

const teams=["wallet","member","devops","data","event"];
const jsonPost=body=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
async function uploadFile(file){const form=new FormData();form.append("file",file);return request("/v1/files",{method:"POST",body:form})}
function fileActions(url){return `<a class="rowbtn" href="${esc(url)}" target="_blank" rel="noopener">查看原文件</a><a class="rowbtn" href="${esc(url)}?download=true" download>下载原文件</a>`}
function newPage(){
 active("new","录入文档","文档");
 app.innerHTML=head("录入文档","先上传原文件，再填写信息并提交索引。支持 Markdown、TXT 和 PDF。",'<a class="btn secondary" href="#/documents">返回文档</a>')+`<section class="panel"><div class="body"><form id="ingest" class="grid"><label class="full">源文件<input id="file" type="file" accept=".md,.markdown,.txt,.pdf" required><span id="uploadstatus" class="help" role="status">选择文件后自动上传。</span></label><label>标题 *<input name="title" required maxlength="500"></label><label>团队<select name="team"><option value="">请选择</option>${teams.map(t=>`<option value="${t}">${t}</option>`).join("")}</select></label><label>项目<input name="project"></label><label>操作人<input name="operator"></label><label class="full">描述<textarea name="description"></textarea></label><label class="full">Metadata JSON Object<textarea name="metadata" spellcheck="false">{}</textarea></label><div class="formactions full"><a class="btn secondary" href="#/documents">取消</a><button id="submitdoc" class="btn" disabled>提交索引</button></div></form></div></section>`;
 const form=$("#ingest"),button=$("#submitdoc"),status=$("#uploadstatus");let uploaded=null,sequence=0;
 $("#file").onchange=async e=>{const token=++sequence,file=e.target.files[0];uploaded=null;button.disabled=true;if(!file){status.textContent="请选择文件";return}status.textContent="上传中…";if(!form.elements.title.value)form.elements.title.value=file.name;try{const result=await uploadFile(file);if(token!==sequence)return;uploaded=result;status.innerHTML=`上传完成 · ${esc(result.filename)} ${fileActions(result.url)}`;button.disabled=false}catch(error){if(token===sequence){status.textContent=`上传失败：${error.message}`;toast(error.message,false)}}};
 form.onsubmit=async e=>{e.preventDefault();await run(button,async()=>{if(!uploaded)throw Error("请先完成文件上传");const data=new FormData(form),metadata=JSON.parse(data.get("metadata")||"{}");if(!metadata||Array.isArray(metadata)||typeof metadata!=="object")throw Error("Metadata 必须是 JSON Object");const title=data.get("title").trim();if(!title)throw Error("标题必填");const payload={file_url:uploaded.url,title,metadata};for(const field of ["team","project","description","operator"])payload[field]=data.get(field).trim()||null;const result=await request("/v1/documents",jsonPost(payload));toast(`文档已提交：${short(result.document_id)}`);location.hash="#/documents"})};
}
function detailPage(id){
 active("documents","文档详情","文档");app.innerHTML=head("文档详情","查看原文件、下载，或上传新文件替换并重新索引。",'<a class="btn secondary" href="#/documents">返回文档列表</a>')+'<div id="detail"><div class="empty">加载中…</div></div>';
 docs().then(()=>{const d=state.documents.find(x=>String(x.document_id)===id);if(!d)throw Error("未找到该文档");$("#detail").innerHTML=`<div class="detail"><section class="panel"><div class="panelhead"><h2>${esc(d.title)}</h2>${badge(d.status)}</div><div class="body grid">${["title","team","project","operator","description"].map(k=>`<label class="${k==="description"?"full":""}">${({title:"标题",team:"团队",project:"项目",operator:"操作人",description:"描述"})[k]}<${k==="description"?"textarea readonly":"input readonly value=\""+esc(d[k]||"")+"\""}>${k==="description"?esc(d[k]||"")+"</textarea>":""}</label>`).join("")}<p class="help full">ID ${esc(d.document_id)} · v${d.version}</p>${d.last_error?`<pre class="chunk full">${esc(d.last_error)}</pre>`:""}<label class="full">Metadata<textarea readonly>${esc(pretty(d.metadata||{}))}</textarea></label></div></section><aside class="panel"><div class="panelhead"><h2>原文件</h2></div><div class="body"><div class="actions">${fileActions(d.file_url)}</div><form id="reindex"><label style="margin-top:20px">替换文件（可选）<input id="newfile" type="file" accept=".md,.markdown,.txt,.pdf"></label><p id="reuploadstatus" class="help" role="status">留空则使用现有文件重建。</p><button class="btn" style="margin-top:12px">提交更新 / 重建</button></form><div class="dangerzone"><button id="remove" class="btn danger">删除文档</button><p class="help">删除文档和索引，保留独立上传的原文件。</p></div></div></aside></div>`;
 const form=$("#reindex"),button=form.querySelector("button"),status=$("#reuploadstatus");let uploaded=null,sequence=0;
 $("#newfile").onchange=async e=>{const token=++sequence,file=e.target.files[0];uploaded=null;button.disabled=!!file;if(!file){status.textContent="将使用现有文件重建";return}status.textContent="上传中…";try{const result=await uploadFile(file);if(token!==sequence)return;uploaded=result;status.textContent=`上传完成：${result.filename}`;button.disabled=false}catch(error){if(token===sequence){status.textContent=`上传失败：${error.message}`;toast(error.message,false)}}};
 form.onsubmit=async e=>{e.preventDefault();await run(button,async()=>{if($("#newfile").files.length&&!uploaded)throw Error("请先完成文件上传");const r=await request(`/v1/documents/${encodeURIComponent(id)}/reindex`,jsonPost({file_url:uploaded?.url||null}));toast(`已提交更新，目标版本 v${r.version}`);detailPage(id)})};
 $("#remove").onclick=e=>{if(confirm(`确认删除文档 ${d.title}？`))run(e.currentTarget,async()=>{await request(`/v1/documents/${encodeURIComponent(id)}`,{method:"DELETE"});toast("已提交删除任务");location.hash="#/documents"})};
 }).catch(e=>{$("#detail").innerHTML='<div class="empty">文档不存在或加载失败</div>';toast(e.message,false)});
}

function searchPage(){active("search","检索");app.innerHTML=head("检索","使用自然语言查询已完成索引的文档，并检查召回分数与 Chunk 来源。")+`<section class="searchbox"><form id="search"><label>问题<textarea id="query" class="query" required placeholder="输入希望从知识库中检索的问题…"></textarea></label><div class="searchcontrols"><div class="topk"><label>Top-K（1–10）<input id="topk" type="number" min="1" max="10" value="5" required></label><span class="help">控制返回的最大结果数</span></div><button class="btn"><i class="ph ph-magnifying-glass"></i>开始检索</button></div></form></section><div class="resultshead"><h2>检索结果</h2><span id="summary" class="help">提交问题后显示结果</span></div><section id="results"></section>`;$("#search").onsubmit=async e=>{e.preventDefault();await run(e.submitter,async()=>{const start=performance.now(),query=$("#query").value.trim(),top_k=Math.max(1,Math.min(10,Number($("#topk").value)));$("#topk").value=top_k;const items=await request("/v1/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,top_k})});$("#summary").textContent=`找到 ${items.length} 条结果 · ${(performance.now()-start).toFixed(0)} ms · Top-K ${top_k}`;$("#results").innerHTML=items.length?items.map((x,i)=>`<article class="result"><div class="rank">${i+1}</div><div class="resultmain"><div class="resulttitle"><strong>${esc(x.title||x.file_url)}</strong><span class="score">${Number(x.score).toFixed(6)}</span></div><p>${esc(x.content)}</p><a class="rowbtn" href="#/chunks?document=${encodeURIComponent(x.document_id)}&chunk=${encodeURIComponent(x.chunk_id)}">查看完整 Chunk →</a></div><div class="resultmeta"><span>文档 ID<br><code title="${esc(x.document_id)}">${esc(short(x.document_id))}</code></span><span>Chunk ID<br><code title="${esc(x.chunk_id)}">${esc(short(x.chunk_id))}</code></span><span>${esc(x.file_url)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</span></div></article>`).join(""):'<div class="panel"><div class="empty">没有召回有效结果</div></div>'})}}

function chunksPage(params){active("chunks","Chunk 查询");app.innerHTML=head("Chunk 查询","使用 Document ID 和 Chunk ID 精确读取 Qdrant 中保存的原始切块。")+`<section class="panel"><div class="panelhead"><div><h2>精确定位</h2><p>两个 UUID 必须来自同一条检索结果。</p></div></div><div class="body"><form id="chunkform" class="grid"><label>Document ID<input id="docid" class="mono" required value="${esc(params.get("document")||"")}" placeholder="完整 Document UUID"></label><label>Chunk ID<input id="chunkid" class="mono" required value="${esc(params.get("chunk")||"")}" placeholder="完整 Chunk UUID"></label><div class="formactions full"><button class="btn"><i class="ph ph-crosshair"></i>读取 Chunk</button></div></form></div></section><section id="chunkresult"></section>`;const submit=b=>run(b,async()=>{const d=$("#docid").value.trim(),c=$("#chunkid").value.trim(),x=await request(`/v1/documents/${encodeURIComponent(d)}/chunks/${encodeURIComponent(c)}`);$("#chunkresult").innerHTML=`<section class="panel"><div class="panelhead"><div><h2>${esc(x.title||"Chunk 内容")}</h2><p>${esc(x.file_url)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</p></div><span class="score">${esc(short(x.chunk_id))}</span></div><div class="body"><pre class="chunk">${esc(x.content)}</pre><p class="help">Metadata · <code>${esc(pretty(x.metadata||{}))}</code></p></div></section>`});$("#chunkform").onsubmit=e=>{e.preventDefault();submit(e.submitter)};if(params.get("document")&&params.get("chunk"))submit($("#chunkform button"))}

function drawHealth(){const grid=$("#healthgrid");if(!grid)return;const deps=state.health?.dependencies;if(!deps){grid.innerHTML='<div class="empty">无法读取依赖状态</div>';return}const labels={postgresql:"PostgreSQL",rabbitmq:"RabbitMQ",qdrant:"Qdrant",ollama:"Ollama",worker:"索引 Worker"};grid.innerHTML=Object.entries({...deps,worker:deps.worker}).map(([n,ok])=>`<div class="healthitem"><div><strong>${esc(labels[n]||n)}</strong>${n==="worker"?'<p class="help">每 10 秒发送心跳，30 秒过期；需有活跃消费者。</p>':""}</div>${ok===undefined?'<span class="badge">未知</span>':`<span class="badge ${ok?"ready":"failed"}">${ok?"正常":"异常"}</span>`}</div>`).join("")}
function systemPage(){active("system","系统状态");app.innerHTML=head("系统状态","检查 API、基础设施及索引 Worker，并查看最近一次 HTTP 响应。",'<button id="refreshhealth" class="btn secondary"><i class="ph ph-arrows-clockwise"></i>重新检查</button>')+`<section class="panel"><div class="panelhead"><div><h2>服务依赖</h2><p>状态来自 GET /health。</p></div></div><div class="body"><div id="healthgrid" class="healthgrid"><div class="empty">检查中…</div></div></div></section><section class="panel"><div class="panelhead"><div><h2>最近 HTTP 响应</h2><p>用于学习与排查接口契约。</p></div><button id="clear" class="btn secondary small">清空</button></div><div class="body"><pre id="log" class="log">${esc(state.last?pretty(state.last):"尚无请求")}</pre></div></section>`;health().then(drawHealth);$("#refreshhealth").onclick=e=>run(e.currentTarget,async()=>{await health();drawHealth();toast("状态已刷新")});$("#clear").onclick=()=>{state.last=null;$("#log").textContent="尚无请求"}}

function route(){clearTimeout(state.timer);document.body.classList.remove("navopen");const raw=(location.hash||"#/documents").slice(1),[path,q=""]=raw.split("?"),s=path.split("/").filter(Boolean),p=new URLSearchParams(q);if(s[0]==="documents"&&s[1]==="new")newPage();else if(s[0]==="documents"&&s[1])detailPage(decodeURIComponent(s[1]));else if(s[0]==="documents")documentsPage();else if(s[0]==="search")searchPage();else if(s[0]==="chunks")chunksPage(p);else if(s[0]==="system")systemPage();else location.hash="#/documents";requestAnimationFrame(()=>app.focus({preventScroll:true}))}
$("#menu").onclick=()=>document.body.classList.toggle("navopen");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.body.classList.remove("navopen"));addEventListener("hashchange",route);health();route();setInterval(health,15000);
