const $=(s,r=document)=>r.querySelector(s),app=$("#app");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const pretty=v=>JSON.stringify(v,null,2),short=v=>String(v||"").slice(0,8);
const state={documents:[],health:null,last:null,timer:null};

function toast(message,ok=true){const n=$("#toast");n.textContent=message;n.className=`show${ok?"":" bad"}`;clearTimeout(n.timer);n.timer=setTimeout(()=>n.className="",4200)}
async function request(path,options={}){const r=await fetch(path,options),type=r.headers.get("content-type")||"",body=type.includes("json")?await r.json():await r.text();state.last={status:r.status,path,body,at:new Date().toLocaleTimeString("zh-CN",{hour12:false})};if(!r.ok){const d=Array.isArray(body?.detail)?body.detail.map(x=>x.msg).join("；"):body?.detail;throw new Error(body?.message||d||`${r.status} ${r.statusText}`)}return body}
async function run(button,fn){if(button)button.disabled=true;try{return await fn()}catch(e){toast(e.message,false);throw e}finally{if(button)button.disabled=false}}
function active(name,label,parent="控制台"){document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.nav===name));$("#crumb").innerHTML=`${esc(parent)} &nbsp;/&nbsp; <strong>${esc(label)}</strong>`}
function head(title,desc,actions=""){return `<div class="pagehead"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${actions?`<div class="actions">${actions}</div>`:""}</div>`}
function badge(s){const m={ready:"已索引",pending:"待处理",indexing:"索引中",failed:"处理失败",deleting:"删除中",deleted:"已删除"};return `<span class="badge ${esc(s)}">${esc(m[s]||s)}</span>`}
async function health(){try{const r=await fetch("/health");state.health=await r.json();const ok=!!state.health.ready;$("#side-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"服务运行中":"服务异常"}`;$("#top-health").innerHTML=`<span class="dot ${ok?"ok":"bad"}"></span>${ok?"全部依赖正常":"存在异常依赖"}`}catch{state.health=null;$("#side-health").innerHTML='<span class="dot bad"></span>API 不可用';$("#top-health").innerHTML='<span class="dot bad"></span>连接失败'}}
async function docs(){state.documents=await request("/v1/documents");return state.documents}

function documentsPage(){active("documents","文档");app.innerHTML=head("文档","管理已录入的文档，查看索引状态并执行更新、重建或删除。",'<a class="btn" href="#/documents/new"><i class="ph ph-plus"></i>录入文档</a>')+`<section id="stats" class="stats"></section><section class="panel"><div class="body"><div class="toolbar"><div class="searchinput"><i class="ph ph-magnifying-glass"></i><input id="filter" type="search" placeholder="搜索标题、来源或 ID"></div><select id="status"><option value="">全部状态</option><option value="ready">已索引</option><option value="pending">待处理</option><option value="indexing">索引中</option><option value="failed">处理失败</option></select><button id="refresh" class="btn secondary"><i class="ph ph-arrows-clockwise"></i>刷新</button></div><div class="tablewrap"><table><thead><tr><th>文档标题 / 来源</th><th>ID</th><th>版本</th><th>状态</th><th>Metadata</th><th>操作</th></tr></thead><tbody id="rows"><tr><td colspan="6" class="empty">加载中…</td></tr></tbody></table></div></div></section>`;
 const draw=()=>{const q=$("#filter").value.toLowerCase(),s=$("#status").value,items=state.documents.filter(d=>(!s||d.status===s)&&(!q||`${d.title||""} ${d.source_uri} ${d.document_id}`.toLowerCase().includes(q))),counts=state.documents.reduce((a,d)=>(a[d.status]=(a[d.status]||0)+1,a),{});$("#stats").innerHTML=[["文档总数",state.documents.length,"files"],["已索引",counts.ready||0,"check-circle"],["处理中",(counts.pending||0)+(counts.indexing||0),"clock-countdown"],["处理失败",counts.failed||0,"warning-circle"]].map(x=>`<div class="stat"><span>${x[0]}<i class="ph ph-${x[2]}"></i></span><strong>${x[1]}</strong></div>`).join("");$("#rows").innerHTML=items.length?items.map(d=>`<tr><td><span class="title">${esc(d.title||"未命名文档")}</span><span class="source">${esc(d.source_uri)}</span></td><td class="mono" title="${esc(d.document_id)}">${esc(short(d.document_id))}</td><td>v${d.version}</td><td>${badge(d.status)}</td><td class="mono">${Object.keys(d.metadata||{}).length?Object.keys(d.metadata).length+" fields":"—"}</td><td><div class="rowactions"><a class="rowbtn" href="#/documents/${encodeURIComponent(d.document_id)}">查看 / 更新</a><button class="rowbtn rebuild" data-id="${esc(d.document_id)}">重建</button><button class="rowbtn danger delete" data-id="${esc(d.document_id)}">删除</button></div></td></tr>`).join(""):'<tr><td colspan="6"><div class="empty"><i class="ph ph-files"></i>没有符合条件的文档</div></td></tr>'};
 const refresh=async b=>run(b,async()=>{await docs();draw();schedule(draw)});$("#filter").oninput=draw;$("#status").onchange=draw;$("#refresh").onclick=e=>refresh(e.currentTarget);$("#rows").onclick=async e=>{const b=e.target.closest("button[data-id]");if(!b)return;if(b.classList.contains("rebuild"))await run(b,async()=>{const r=await request(`/v1/documents/${encodeURIComponent(b.dataset.id)}/reindex`,{method:"POST"});toast(`已提交重建，目标版本 v${r.version}`);await docs();draw()});if(b.classList.contains("delete")&&confirm(`确认删除文档 ${b.dataset.id}？此操作会同时清除索引。`))await run(b,async()=>{await request(`/v1/documents/${encodeURIComponent(b.dataset.id)}`,{method:"DELETE"});toast("已提交删除任务");await docs();draw()})};docs().then(()=>{draw();schedule(draw)}).catch(e=>{$("#rows").innerHTML='<tr><td colspan="6" class="empty">文档加载失败</td></tr>';toast(e.message,false)})}
function schedule(draw){clearTimeout(state.timer);if(state.documents.some(d=>["pending","indexing","deleting"].includes(d.status)))state.timer=setTimeout(async()=>{try{await docs();draw();schedule(draw)}catch{}},3000)}

function newPage(){active("new","录入文档","文档");app.innerHTML=head("录入文档","上传一个源文件并提交异步索引任务。支持 Markdown、TXT 和 PDF。",'<a class="btn secondary" href="#/documents"><i class="ph ph-arrow-left"></i>返回文档</a>')+`<section class="panel"><div class="panelhead"><div><h2>文档信息</h2><p>文件会经过解析、清洗、切块和向量化。</p></div></div><div class="body"><form id="ingest" class="grid"><label class="full">源文件<input id="file" name="file" type="file" accept=".md,.markdown,.txt,.pdf" required><span class="help">选择 Markdown、TXT 或 PDF 文件。</span></label><label>Source URI<input id="uri" name="source_uri" required placeholder="例如 docs/rag-guide.pdf"></label><label>文档标题（可选）<input name="title" placeholder="例如 RAG 技术指南"></label><label class="full">Metadata JSON Object<textarea name="metadata" spellcheck="false">{}</textarea><span class="help">必须是合法 JSON 对象。</span></label><div class="formactions full"><a class="btn secondary" href="#/documents">取消</a><button class="btn"><i class="ph ph-upload-simple"></i>录入并提交索引</button></div></form></div></section>`;$("#file").onchange=e=>{if(!$("#uri").value&&e.target.files[0])$("#uri").value=e.target.files[0].name};$("#ingest").onsubmit=async e=>{e.preventDefault();await run(e.submitter,async()=>{const metadata=JSON.parse(e.target.metadata.value.trim()||"{}");if(!metadata||Array.isArray(metadata)||typeof metadata!=="object")throw new Error("Metadata 必须是 JSON Object");const form=new FormData(e.target);form.set("metadata",JSON.stringify(metadata));const r=await request("/v1/documents",{method:"POST",body:form});toast(`文档已提交：${short(r.document_id)}`);location.hash="#/documents"})}}

function detailPage(id){active("documents","文档详情","文档");app.innerHTML=head("文档详情","查看文档信息，替换源文件或基于已保存内容重建索引。",'<a class="btn secondary" href="#/documents"><i class="ph ph-arrow-left"></i>返回文档列表</a>')+'<div id="detail"><section class="panel"><div class="empty">正在加载文档…</div></section></div>';docs().then(()=>{const d=state.documents.find(x=>String(x.document_id)===id);if(!d)throw new Error("未找到该文档");$("#detail").innerHTML=`<div class="detail"><section class="panel"><div class="body"><div class="identity"><div class="fileicon"><i class="ph ph-file-text"></i></div><div><h2>${esc(d.title||"未命名文档")}</h2><p>${esc(d.source_uri)}</p></div></div><div class="metastrip"><span>ID <strong class="mono">${esc(d.document_id)}</strong></span><span>版本 <strong>v${d.version}</strong></span><span>${badge(d.status)}</span></div><section class="panel" style="margin-top:22px;box-shadow:none"><div class="panelhead"><h2>基本信息</h2></div><div class="body grid"><label>标题<input readonly value="${esc(d.title||"")}"></label><label>版本<input readonly value="v${d.version}"></label><label class="full">Source URI<input readonly value="${esc(d.source_uri)}"></label><label class="full">Metadata<textarea readonly>${esc(pretty(d.metadata||{}))}</textarea></label></div></section></div></section><aside class="panel"><div class="panelhead"><h2>文件操作</h2></div><div class="body"><form id="reindex"><label class="drop"><i class="ph ph-cloud-arrow-up"></i><strong>选择新文件替换当前内容</strong><span>留空则使用已保存内容重建</span><input id="newfile" type="file" accept=".md,.markdown,.txt,.pdf" style="margin-top:14px"></label><button class="btn" style="width:100%;margin-top:12px"><i class="ph ph-arrows-clockwise"></i>提交更新 / 重建</button></form><div class="dangerzone"><button id="remove" class="btn danger" style="width:100%"><i class="ph ph-trash"></i>删除文档</button><p class="help">删除会同时清理事实数据和向量索引。</p></div></div></aside></div>`;$("#reindex").onsubmit=async e=>{e.preventDefault();await run(e.submitter,async()=>{const file=$("#newfile").files[0],o={method:"POST"};if(file){const f=new FormData();f.append("file",file);o.body=f}const r=await request(`/v1/documents/${encodeURIComponent(id)}/reindex`,o);toast(`已提交更新，目标版本 v${r.version}`);setTimeout(route,500)})};$("#remove").onclick=async e=>{if(confirm(`确认删除文档 ${id}？`))await run(e.currentTarget,async()=>{await request(`/v1/documents/${encodeURIComponent(id)}`,{method:"DELETE"});toast("已提交删除任务");location.hash="#/documents"})}}).catch(e=>{$("#detail").innerHTML='<section class="panel"><div class="empty">文档不存在或加载失败</div></section>';toast(e.message,false)})}

function searchPage(){active("search","检索");app.innerHTML=head("检索","使用自然语言查询已完成索引的文档，并检查召回分数与 Chunk 来源。")+`<section class="searchbox"><form id="search"><label>问题<textarea id="query" class="query" required placeholder="输入希望从知识库中检索的问题…"></textarea></label><div class="searchcontrols"><div class="topk"><label>Top-K（1–10）<input id="topk" type="number" min="1" max="10" value="5" required></label><span class="help">控制返回的最大结果数</span></div><button class="btn"><i class="ph ph-magnifying-glass"></i>开始检索</button></div></form></section><div class="resultshead"><h2>检索结果</h2><span id="summary" class="help">提交问题后显示结果</span></div><section id="results"></section>`;$("#search").onsubmit=async e=>{e.preventDefault();await run(e.submitter,async()=>{const start=performance.now(),query=$("#query").value.trim(),top_k=Math.max(1,Math.min(10,Number($("#topk").value)));$("#topk").value=top_k;const items=await request("/v1/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query,top_k})});$("#summary").textContent=`找到 ${items.length} 条结果 · ${(performance.now()-start).toFixed(0)} ms · Top-K ${top_k}`;$("#results").innerHTML=items.length?items.map((x,i)=>`<article class="result"><div class="rank">${i+1}</div><div class="resultmain"><div class="resulttitle"><strong>${esc(x.title||x.source_uri)}</strong><span class="score">${Number(x.score).toFixed(6)}</span></div><p>${esc(x.content)}</p><a class="rowbtn" href="#/chunks?document=${encodeURIComponent(x.document_id)}&chunk=${encodeURIComponent(x.chunk_id)}">查看完整 Chunk →</a></div><div class="resultmeta"><span>文档 ID<br><code title="${esc(x.document_id)}">${esc(short(x.document_id))}</code></span><span>Chunk ID<br><code title="${esc(x.chunk_id)}">${esc(short(x.chunk_id))}</code></span><span>${esc(x.source_uri)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</span></div></article>`).join(""):'<div class="panel"><div class="empty">没有召回有效结果</div></div>'})}}

function chunksPage(params){active("chunks","Chunk 查询");app.innerHTML=head("Chunk 查询","使用 Document ID 和 Chunk ID 精确读取 PostgreSQL 中保存的原始切块。")+`<section class="panel"><div class="panelhead"><div><h2>精确定位</h2><p>两个 UUID 必须来自同一条检索结果。</p></div></div><div class="body"><form id="chunkform" class="grid"><label>Document ID<input id="docid" class="mono" required value="${esc(params.get("document")||"")}" placeholder="完整 Document UUID"></label><label>Chunk ID<input id="chunkid" class="mono" required value="${esc(params.get("chunk")||"")}" placeholder="完整 Chunk UUID"></label><div class="formactions full"><button class="btn"><i class="ph ph-crosshair"></i>读取 Chunk</button></div></form></div></section><section id="chunkresult"></section>`;const submit=b=>run(b,async()=>{const d=$("#docid").value.trim(),c=$("#chunkid").value.trim(),x=await request(`/v1/documents/${encodeURIComponent(d)}/chunks/${encodeURIComponent(c)}`);$("#chunkresult").innerHTML=`<section class="panel"><div class="panelhead"><div><h2>${esc(x.title||"Chunk 内容")}</h2><p>${esc(x.source_uri)} · lines ${x.start_line??"?"}–${x.end_line??"?"}</p></div><span class="score">${esc(short(x.chunk_id))}</span></div><div class="body"><pre class="chunk">${esc(x.content)}</pre><p class="help">Metadata · <code>${esc(pretty(x.metadata||{}))}</code></p></div></section>`});$("#chunkform").onsubmit=e=>{e.preventDefault();submit(e.submitter)};if(params.get("document")&&params.get("chunk"))submit($("#chunkform button"))}

function systemPage(){active("system","系统状态");app.innerHTML=head("系统状态","检查 API 及基础设施依赖，并查看最近一次 HTTP 响应。",'<button id="refreshhealth" class="btn secondary"><i class="ph ph-arrows-clockwise"></i>重新检查</button>')+`<section class="panel"><div class="panelhead"><div><h2>服务依赖</h2><p>状态来自 GET /health。</p></div></div><div class="body"><div id="healthgrid" class="healthgrid"><div class="empty">检查中…</div></div></div></section><section class="panel"><div class="panelhead"><div><h2>最近 HTTP 响应</h2><p>用于学习与排查接口契约。</p></div><button id="clear" class="btn secondary small">清空</button></div><div class="body"><pre id="log" class="log">${esc(state.last?pretty(state.last):"尚无请求")}</pre></div></section>`;const draw=()=>{$("#healthgrid").innerHTML=state.health?.dependencies?Object.entries(state.health.dependencies).map(([n,ok])=>`<div class="healthitem"><strong>${esc(n)}</strong>${badge(ok?"ready":"failed")}</div>`).join(""):'<div class="empty">无法读取依赖状态</div>'};health().then(draw);$("#refreshhealth").onclick=e=>run(e.currentTarget,async()=>{await health();draw();toast("状态已刷新")});$("#clear").onclick=()=>{state.last=null;$("#log").textContent="尚无请求"}}

function route(){clearTimeout(state.timer);document.body.classList.remove("navopen");const raw=(location.hash||"#/documents").slice(1),[path,q=""]=raw.split("?"),s=path.split("/").filter(Boolean),p=new URLSearchParams(q);if(s[0]==="documents"&&s[1]==="new")newPage();else if(s[0]==="documents"&&s[1])detailPage(decodeURIComponent(s[1]));else if(s[0]==="documents")documentsPage();else if(s[0]==="search")searchPage();else if(s[0]==="chunks")chunksPage(p);else if(s[0]==="system")systemPage();else location.hash="#/documents";requestAnimationFrame(()=>app.focus({preventScroll:true}))}
$("#menu").onclick=()=>document.body.classList.toggle("navopen");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.body.classList.remove("navopen"));addEventListener("hashchange",route);health();route();setInterval(health,15000);
